### ISSUE TITLE
Runtime error: out of gas

### ISSUE THREAD

**Issue by saddam1997** [BravoNatalie/NFT-Marketplace#1]
Hi,

I am getting this error. Please find  screenshot.

![image](https://user-images.githubusercontent.com/18419524/153021127-e58c2bad-7cef-4f90-bf7e-68c541aca208.png)

**Comment by saddam1997** [comment]
Issue fixed. 

I am connecting with wrong metamask account.

**Comment by hrithikAd** [comment]
> 

How did you fix bro?
